config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :auto_buys do
    collection do
      get :stop_working
      get :retry_job
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  root 'auto_buys#index'
end

app/controllers/auto_buys_controller.rb
class AutoBuysController < ApplicationController
  def index
    @background_jobs = BackgroundJob.all
  end

  def new
    @background_job = BackgroundJob.new(job_name: "AutoBuyWorker")
    @background_job.build_account
  end

  def create
    @background_job = BackgroundJob.new(background_job_params)

    if @background_job.account.save && @background_job.save
      redirect_to auto_buys_path, notice: "Udało Ci się utworzyć zadanie automatycznego kupowania!"
    else
      render 'new'
    end
  end

  def edit
    @background_job = BackgroundJob.find(params[:id])
  end

  def update
    @background_job = BackgroundJob.find(params[:id])

    if @background_job.update_attributes(background_job_params)
      redirect_to auto_buys_path, notice: "Udało Ci się edytować zadanie automatycznego kupowania!"
    else
      render 'edit'
    end
  end

  def destroy
    @background_job = BackgroundJob.find(params[:id])

    if @background_job.status.in?(["error", "finished"]) && @background_job.delete
      redirect_to auto_buys_path, notice: "Udało Ci się usunąć zadania automatycznego kupowania"
    else
      redirect_to auto_buys_path, notice: "Nie udało Ci się usunąć zadania automatycznego kupowania"
    end
  end

  def stop_working
    @background_job = BackgroundJob.find(params[:id])

    if @background_job.stop_working
      redirect_to auto_buys_path, notice: "Udało Ci się zatrzymać zadania automatycznego kupowania"
    else
      redirect_to auto_buys_path, notice: "Nie udało Ci się zatrzymać zadania automatycznego kupowania"
    end
  end

  def retry_job
    @background_job = BackgroundJob.find(params[:id])

    @background_job.update_attributes(status: "new", log: nil)
    @background_job.start_worker

    redirect_to auto_buys_path, notice: "Zadanie przekazane do ponownego uruchomienia."
  end

  def show
    @background_job = BackgroundJob.find(params[:id])
  end

  private
    def background_job_params
      params.require(:background_job).permit(:job_name, :username_for_job, :interval, :search_products_by, account_attributes: [:username, :password_first, :password_second])
    end
end

app/views/auto_buys/edit.html.erb
<%= form_for(@background_job, url: auto_buy_path, method: :put) do |f| %>
  <%= f.hidden_field :job_name %>

  <p>
    <%= f.label :username_for_job %><br />
    <%= f.text_field :username_for_job %>
  </p>

  <p>
    <%= f.label :interval %><br />
    <%= f.text_field :interval %>
  </p>

  <p>
    <%= f.label :search_products_by %><br />
    <%= f.text_field :search_products_by %>
  </p>

  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/auto_buys/index.html.erb
Ilość zadań aktualnie działających: <%= AutoBuyWorker.count_jobs_running %> </br>

<% if @background_jobs.any? %>
  <table class="table table-condensed table-striped">
    <tr>
      <th>ID</th>
      <th>Status</th>
      <th>Działa zadań</th>
      <th>Nazwa zadania</th>
      <th>Interwał zadania</th>
      <th>Nazwa użytkownika allegro</th>
      <th>Kup przedmioty z tytułem</th>
      <th span="2"></th>
      <th span="2"></th>
      <th></th>
    </tr>
    <% @background_jobs.each do |background_job| %>
      <tr>
        <td><%= background_job.id %></td>
        <td style="<% (background_job.last_update_in_sec > 15) && background_job.status.in?(["new", "working"]) ? 'color: red;' : 'color: green;' %>"><%= background_job.status %></td>
        <td><%= AutoBuyWorker.count_jobs_running_with_params({ "background_job_id"=> background_job.id }) %></td>
        <td><%= background_job.job_name %></td>
        <td><%= background_job.interval %></td>
        <td><%= background_job.username_for_job %></td>
        <td><%= background_job.search_products_by %></td>
        <td style="display: inline-block;">
          <%= link_to "Info", auto_buy_path(id: background_job.id), class: 'btn btn-info' %>
          <%= link_to "Edytuj", edit_auto_buy_path(id: background_job.id), class: 'btn btn-info' %>
        </td>
        <td style="display: inline-block;">
          <%= link_to "Ponów", retry_job_auto_buys_path(id: background_job.id), class: 'btn btn-info' %>
          <%= link_to "Zakończ", stop_working_auto_buys_path(id: background_job.id), class: 'btn btn-warning' %>
        </td>
        <td style="display: inline-block;">
          <%= button_to "Usuń", auto_buy_path(:id => background_job.id), :method => :delete, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  Nie ma żadnych zadań, stwórz nowe: </br>
  <%= link_to "Nowe zadanie", new_auto_buy_path %>
<% end %>

app/views/auto_buys/new.html.erb
<%= form_for(@background_job, url: auto_buys_path, html: { class: "form-horizontal center" }) do |f| %>
  <%= f.hidden_field :job_name %>

  <% #f.error_messages %>

  <%= f.fields_for :account do |account| %>
    <p>
      <%= account.label :username %><br />
      <%= account.text_field :username, placeholder: "uzytkownik allegro" %>
    </p>

    <p>
      <%= account.label :password_first %><br />
      <%= account.password_field :password_first, placeholder: "haslo allegro" %>
    </p>

    <p>
      <%= account.label :password_second %><br />
      <%= account.password_field :password_second, placeholder: "haslo allegro" %>
    </p>
  <% end %>

  <p>
    <%= f.label :username_for_job %><br />
    <%= f.text_field :username_for_job, placeholder: "użytkownik, np. 'terg_abc'" %>
  </p>

  <p>
    <%= f.label :interval %><br />
    <%= f.text_field :interval, placeholder: "liczba, np. '1'" %>
  </p>

  <p>
    <%= f.label :search_products_by %><br />
    <%= f.text_field :search_products_by, placeholder: "nazwa, np. 'woda; sok'" %>
  </p>

  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/auto_buys/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      ID
    </div>
    <div class="col-sm-8">
      <%= @background_job.id %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Status
    </div>
    <div class="col-sm-8">
      <%= @background_job.status %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Średnia dlugość wykonania
    </div>
    <div class="col-sm-8">
      <%= "#{@background_job.last_runtime_sec.to_f.round(3)} sekund" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Ostatnia zmiana
    </div>
    <div class="col-sm-8">
      <%= "#{@background_job.last_update_in_sec.to_f.round(3)} sekund temu" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Sleep interval
    </div>
    <div class="col-sm-8">
      <%= @background_job.interval %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Username for job
    </div>
    <div class="col-sm-8">
      <%= @background_job.username_for_job %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Search products by
    </div>
    <div class="col-sm-8">
      <%= @background_job.search_products_by %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Started at
    </div>
    <div class="col-sm-8">
      <%= @background_job.created_at %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      Log
    </div>
    <div class="col-sm-8">
      <%= @background_job.log.gsub(/\n/, '<br>').html_safe if @background_job.log.present? %>
    </div>
  </div>

</div>